services:
  web:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start
    volumes:
    - .:/code
    ports:
    - 8000:8000
    env_file:
    - .env
    depends_on:
    - db
  db:
    image: postgres:15.7-alpine
    container_name: ebook_db
    ports:
    - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
volumes:
  postgres_data:
    name: ebook_postgres_data